-- Assets migrations bundle (psql \i includes)
\i /app/packages/infra-postgres/src/migrations/020_assets_management_phase2.sql
\i /app/packages/infra-postgres/src/migrations/030_maintenance_warehouse.sql
\i /app/packages/infra-postgres/src/migrations/035_asset_category_spec_defs.sql
\i /app/packages/infra-postgres/src/migrations/036_asset_category_spec_versions.sql
\i /app/packages/infra-postgres/src/migrations/037_cmdb.sql
\i /app/packages/infra-postgres/src/migrations/038_stock_documents_approval_status.sql
\i /app/packages/infra-postgres/src/migrations/039_workflow_issue_stock_request_type.sql
\i /app/packages/infra-postgres/src/migrations/040_cmdb_change_management.sql
\i /app/packages/infra-postgres/src/migrations/041_cmdb_relationship_type_column_alignment.sql
\i /app/packages/infra-postgres/src/migrations/042_asset_status_catalogs.sql

\i /app/db/migrations/007_cmdb_core.sql
\i /app/db/migrations/025_add_asset_spec.sql
\i /app/db/migrations/026_phase1_workflow_foundation.sql
\i /app/db/migrations/030_licenses_module.sql
\i /app/db/migrations/031_accessories_module.sql
\i /app/db/migrations/032_consumables_module.sql
\i /app/db/migrations/033_components_module.sql
\i /app/db/migrations/034_checkout_module.sql
\i /app/db/migrations/035_requests_module.sql
\i /app/db/migrations/036_audit_module.sql
\i /app/db/migrations/037_labels_module.sql
\i /app/db/migrations/038_depreciation_module.sql
\i /app/db/migrations/039_reports_alerts_module.sql
\i /app/db/migrations/040_messaging_hub.sql
\i /app/db/migrations/041_asset_status_catalog.sql
\i /app/db/migrations/042_workflow_automation.sql
\i /app/db/migrations/043_analytics_dashboard.sql
\i /app/db/migrations/044_cmdb_enhancement.sql
\i /app/db/migrations/045_integration_hub.sql
\i /app/db/migrations/046_security_compliance.sql
\i /app/db/migrations/047_documents_module.sql
\i /app/db/migrations/048_rename_spec_defs_table.sql
\i /app/db/migrations/049_warehouse_improvements.sql
\i /app/db/migrations/050_rbac_permissions.sql
\i /app/db/migrations/051_rbac_ad_model.sql
\i /app/db/migrations/052_wf_module.sql
\i /app/db/migrations/053_inv_enhancements.sql
\i /app/db/migrations/054_asset_warehouse_link.sql
\i /app/db/migrations/055_stock_receipt_issue_enhancements.sql
\i /app/db/migrations/056_wf_request_lines.sql
\i /app/db/migrations/057_wf_enhancements.sql